import numpy as np
from scipy import ndimage as nd
from skimage import feature as skft
import skimage.morphology as skmorph
from scipy.ndimage import morphology

def mesh_3d_grid(x, y, z):
    x = np.asarray(x)
    y = np.asarray(y)
    z = np.asarray(z)
    row, col, hei = len(y), len(x), len(z)
    x = x.reshape(1, 1, col)
    y = y.reshape(1, row, 1)
    z = z.reshape(hei, 1, 1)
    X = x.repeat(row, 1)
    X = X.repeat(hei, 0)
    Y = y.repeat(col, 2)
    Y = y.repeat(hei, 0)
    Z = z.repeat(row, 1)
    Z = Z.repeat(col, 2)
    return X, Y, Z

def ball(radius, dtype=np.uint8):
    """Generate a ball structure element"""
    L = np.linspace(-radius, radius, 2*radius+1)
    X, Y, Z = mesh_3d_grid(L, L, L)
    s = X**2 + Y**2 + Z**2
    return np.array(s <= radius * radius, dtype=dtype)

def opening(src, r=2):
    se = ball(r)
    result = nd.grey_opening(src, footprint=se)
    return result

def local_maximum(data, dist=1):
    lmax = np.zeros(data.shape)
    p = skft.peak_local_max(data, dist).T
    p = (np.array(p[0]), np.array(p[1]), np.array(p[2]))
    lmax[p] = 1
    return lmax

def roi_filtering(src, ref):
    mask = ref > 0
    all_roi = np.unique(src[mask])
    result = np.zeros(src.shape)
    for roi in all_roi:
        result[src==roi] = roi
    return result

#generated by zgf------------------------------------------------------------
def binaryzation(data,threshold):
    xmax = data.shape[0]
    ymax = data.shape[1]
    zmax = data.shape[2]

    for x in range(0,xmax):
        for y in range(0,ymax):
            for z in range(0,zmax):
                if data[x,y,z] > threshold:
                    data[x,y,z] = 1
                else:
                    data[x,y,z] = 0
    return data

def binary_erosion_3D(source_data,structure_array,iterations_num,border_value_input):
    new_vol = source_data.copy()
    for index in range(0,source_data.shape[1]):
        new_vol[:,index,:] = morphology.binary_erosion(source_data[:,index,:],structure=structure_array,iterations=iterations_num,border_value=border_value_input)

    return new_vol

def binary_dilation_3D(source_data,structure_array,iterations_num,border_value_input):
    new_vol = source_data.copy()
    for index in range(0,source_data.shape[1]):
        new_vol[:,index,:] = morphology.binary_dilation(source_data[:,index,:],structure=structure_array,iterations=iterations_num,border_value=border_value_input)

    return new_vol

def grey_erosion_3D(source_data,size,mode,cval):
    new_vol = source_data.copy()
    for index in range(0,source_data.shape[1]):
        new_vol[:,index,:] = morphology.grey_erosion(source_data[:,index,:],size=size,mode=mode,cval=cval)

    return new_vol

def grey_dilation_3D(source_data,size,mode,cval):
    new_vol = source_data.copy()
    for index in range(0,source_data.shape[1]):
        new_vol[:,index,:] = morphology.grey_dilation(source_data[:,index,:],size=size,mode=mode,cval=cval)

    return new_vol

#generated by zgf------------------------------------------------------------
